var documenterSearchIndex = {"docs": [

{
    "location": "index.html#",
    "page": "Home",
    "title": "Home",
    "category": "page",
    "text": ""
},

{
    "location": "index.html#OnlinePCA.jl-Documentation-1",
    "page": "Home",
    "title": "OnlinePCA.jl Documentation",
    "category": "section",
    "text": ""
},

{
    "location": "index.html#Overview-1",
    "page": "Home",
    "title": "Overview",
    "category": "section",
    "text": "OnlinePCA.jl binarizes CSV file, summarizes the information of data matrix and, performs some online-PCA functions for extreamly large scale matrix.Online PCA are performed as following four steps.Step.1 Binarization : We asssume that the data is matrix filled in integar count value and saved as comma-separated CSV file. The CSV file is converted to Julia binary file by csv2bin function. This step extremely accelerates I/O speed.\nStep.2 Summarization : sumr function parses the binary file and then extract some summary statistics in each row and each column. The information is used by Step.2.\nStep.3 Online PCA : Some online PCA functions can be performed against the binary file. By using mean vector of each row generated by Step.2, row-wise centering (c.f. --meanlist option) is performed. Likewise, sum vector of each columns are used column-wise normalization (c.f. --liblist option). oja, ccipca, gd, rsgd, svrg, and rsvrg are implemented.All programs are available as Julia API (OnlinePCA.jl (Julia API)) and command line tool (OnlinePCA.jl (Command line tool))."
},

{
    "location": "index.html#Reference-1",
    "page": "Home",
    "title": "Reference",
    "category": "section",
    "text": ""
},

{
    "location": "index.html#Algorithms-1",
    "page": "Home",
    "title": "Algorithms",
    "category": "section",
    "text": "SGD-PCA（Oja\'s method) : Erkki Oja et. al., 1985, Erkki Oja, 1992\nCCIPCA : Juyang Weng et. al., 2003\nGD-PCA : None (Just for comparision with other methods)\nRSGD-PCA : Silvere Bonnabel, 2013\nSVRG-PCA : Ohad Shamir, 2015\nRSVRG-PCA : Hongyi Zhang, et. al., 2016, Hiroyuki Sato, et. al., 2017"
},

{
    "location": "index.html#Learning-Parameter-Scheduling-1",
    "page": "Home",
    "title": "Learning Parameter Scheduling",
    "category": "section",
    "text": "Robbins-Monro : Herbert Robbins, et. al., 1951\nMomentum : Ning Qian, 1999\nNesterov\'s Accelerated Gradient Descent（NAG） : Nesterov, 1983\nADAGRAD : John Duchi, et. al., 2011"
},

{
    "location": "index.html#Identifying-Highly-Variable-Genes-1",
    "page": "Home",
    "title": "Identifying Highly Variable Genes",
    "category": "section",
    "text": "Highly Variable Genes"
},

{
    "location": "juliaapi.html#",
    "page": "Julia API",
    "title": "Julia API",
    "category": "page",
    "text": ""
},

{
    "location": "juliaapi.html#OnlinePCA.jl-(Julia-API)-1",
    "page": "Julia API",
    "title": "OnlinePCA.jl (Julia API)",
    "category": "section",
    "text": ""
},

{
    "location": "juliaapi.html#OnlinePCA.csv2bin-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.csv2bin",
    "category": "method",
    "text": "csv2bin(;csvfile::AbstractString=\"\", binfile::AbstractString=\"\")\n\nConvert a CSV file to Julia Binary file.\n\ncsvfile and binfile are specified such as Data.csv and Data.dat, respectively.\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#Binarization-1",
    "page": "Julia API",
    "title": "Binarization",
    "category": "section",
    "text": "csv2bin(;csvfile::AbstractString=\"\", binfile::AbstractString=\"\")"
},

{
    "location": "juliaapi.html#OnlinePCA.sumr-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.sumr",
    "category": "method",
    "text": "sumr(;binfile::AbstractString=\"\", outdir::AbstractString=\".\", pseudocount::Number=1.0)\n\nExtract the summary information of data matrix.\n\nbinfile is a Julia Binary file generated by csv2bin function.\n\noutdir is specified the directory you want to save the result.\n\npseudocount is specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\n\nOutput Files\n\nSample_NoCounts.csv : Sum of counts in each column.\nFeature_Means.csv : Mean in each row.\nFeature_LogMeans.csv : Log10(Mean+pseudocount) in each row.\nFeature_Vars.csv : Sample variance in each row.\nFeature_CV2s.csv : Coefficient of Variation in each row.\nFeature_NoZeros.csv : Number of zero-elements in each row.\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#Summarization-1",
    "page": "Julia API",
    "title": "Summarization",
    "category": "section",
    "text": "sumr(;binfile::AbstractString=\"\", outdir::AbstractString=\".\", pseudocount::Number=1.0)"
},

{
    "location": "juliaapi.html#OnlinePCA.filtering-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.filtering",
    "category": "method",
    "text": "filtering(;input::AbstractString=\"\", featurelist::AbstractString=\"\", samplelist::AbstractString=\"\", thr1::Number=0, thr2::Number=0, direct1::AbstractString=\"+\", direct2::AbstractString=\"+\", outdir::AbstractString=\".\")\n\nThis function filters the genes by some standards such as mean or variance of the genes.\n\nInput Arguments\n\ninput : A Julia Binary file generated by csv2bin function.\nfeaturelist : A row-wise summary data such as. The CSV files are generated by csv2bin function.\nthr : The threshold to reject low-signal feature.\noutdir : The directory specified the directory you want to save the result.\n\nOutput Files\n\nfiltered.zst : Filtered binary file.\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#Filtering-1",
    "page": "Julia API",
    "title": "Filtering",
    "category": "section",
    "text": "filtering(;input::AbstractString=\"\", featurelist::AbstractString=\"\", samplelist::AbstractString=\"\", thr1::Number=0, thr2::Number=0, direct1::AbstractString=\"+\", direct2::AbstractString=\"+\", outdir::AbstractString=\".\")"
},

{
    "location": "juliaapi.html#OnlinePCA.hvg-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.hvg",
    "category": "method",
    "text": "hvg(;binfile::AbstractString=\"\", rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", rowcv2list::AbstractString=\"\", outdir::AbstractString=\".\")\n\nThis function perform highly variable genes, which is an feature selection method in scRNA-seq studies.\n\nInput Arguments\n\nbinfile is a Julia Binary file generated by csv2bin function.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by sumr functions.\nrowcv2list : The cv2 of each row of matrix. The CSV file is generated by sumr functions.\noutdir : The directory specified the directory you want to save the result.\n\nOutput Files\n\nHVG_useForFit.csv : Parameters to estimate the highly variable genes.\nHVG_a0.csv : Parameters to estimate the highly variable genes.\nHVG_a1.csv : Parameters to estimate the highly variable genes.\nHVG_afits.csv : Parameters to estimate the highly variable genes.\nHVG_varFitRatio.csv : Parameters to estimate the highly variable genes.\nHVG_df.csv : Parameters to estimate the highly variable genes.\nHVG_pval.csv : Parameters to estimate the highly variable genes.\n\nReference\n\nHighly Variable Genes\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#Identifying-Highly-Variable-Genes-1",
    "page": "Julia API",
    "title": "Identifying Highly Variable Genes",
    "category": "section",
    "text": "hvg(;binfile::AbstractString=\"\", rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", rowcv2list::AbstractString=\"\", outdir::AbstractString=\".\")"
},

{
    "location": "juliaapi.html#OnlinePCA.oja-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.oja",
    "category": "method",
    "text": "oja(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by stochastic gradient descent method, also known as Oja\'s method.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nscheduling : Learning parameter scheduling. robbins-monro, momentum, nag, and adagrad are available.\ng : The parameter that is used when scheduling is specified as nag.\nepsilon : The parameter that is used when scheduling is specified as adagrad.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every evalfreq (e.g. 5000) iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\nReference\n\nSGD-PCA（Oja\'s method) : Erkki Oja et. al., 1985, Erkki Oja, 1992\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#Oja-1",
    "page": "Julia API",
    "title": "Oja",
    "category": "section",
    "text": "oja(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "juliaapi.html#OnlinePCA.ccipca-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.ccipca",
    "category": "method",
    "text": "ccipca(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-15, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by candid covariance-free incremental PCA.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every evalfreq (e.g. 5000) iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\nReference\n\nCCIPCA : Juyang Weng et. al., 2003\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#CCIPCA-1",
    "page": "Julia API",
    "title": "CCIPCA",
    "category": "section",
    "text": "ccipca(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-15, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "juliaapi.html#OnlinePCA.gd-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.gd",
    "category": "method",
    "text": "gd(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by gradient descent method.\n\nThe convergence is relatively slower than the other online PCA methods.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nscheduling : Learning parameter scheduling. robbins-monro, momentum, nag, and adagrad are available.\ng : The parameter that is used when scheduling is specified as nag.\nepsilon : The parameter that is used when scheduling is specified as adagrad.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every 1000 iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#GD-1",
    "page": "Julia API",
    "title": "GD",
    "category": "section",
    "text": "gd(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "juliaapi.html#OnlinePCA.rsgd-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.rsgd",
    "category": "method",
    "text": "rsgd(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by Riemannian stochastic gradient descent method.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nscheduling : Learning parameter scheduling. robbins-monro, momentum, nag, and adagrad are available.\ng : The parameter that is used when scheduling is specified as nag.\nepsilon : The parameter that is used when scheduling is specified as adagrad.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every evalfreq (e.g. 5000) iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\nReference\n\nRSGD-PCA : Silvere Bonnabel, 2013\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#RSGD-1",
    "page": "Julia API",
    "title": "RSGD",
    "category": "section",
    "text": "rsgd(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "juliaapi.html#OnlinePCA.svrg-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.svrg",
    "category": "method",
    "text": "svrg(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by variance-reduced stochastic gradient descent method, also known as VR-PCA.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nscheduling : Learning parameter scheduling. robbins-monro, momentum, nag, and adagrad are available.\ng : The parameter that is used when scheduling is specified as nag.\nepsilon : The parameter that is used when scheduling is specified as adagrad.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every evalfreq (e.g. 5000) iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\nReference\n\nSVRG-PCA : Ohad Shamir, 2015\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#SVRG-1",
    "page": "Julia API",
    "title": "SVRG",
    "category": "section",
    "text": "svrg(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\", colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "juliaapi.html#OnlinePCA.rsvrg-Tuple{}",
    "page": "Julia API",
    "title": "OnlinePCA.rsvrg",
    "category": "method",
    "text": "rsvrg(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)\n\nOnline PCA solved by Riemannian variance-reduced stochastic gradient descent method.\n\nInput Arguments\n\ninput : Julia Binary file generated by OnlinePCA.csv2bin function.\noutdir : The directory specified the directory you want to save the result.\nscale : {log,ftt,raw}-scaling of the value.\npseudocount : The number specified to avoid NaN by log10(0) and used when Feature_LogMeans.csv <log10(mean+pseudocount) value of each feature> is generated.\nrowmeanlist : The mean of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\nrowvarlist : The variance of each row of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ncolsumlist : The sum of counts of each columns of matrix. The CSV file is generated by OnlinePCA.sumr functions.\ndim : The number of dimension of PCA.\nstepsize : The parameter used in every iteration.\nnumepoch : The number of epoch.\nscheduling : Learning parameter scheduling. robbins-monro, momentum, nag, and adagrad are available.\ng : The parameter that is used when scheduling is specified as nag.\nepsilon : The parameter that is used when scheduling is specified as adagrad.\nlower : Stopping Criteria (When the relative change of error is below this value, the calculation is terminated)\nupper : Stopping Criteria (When the relative change of error is above this value, the calculation is terminated)\nevalfreq : Evaluation Frequency of Reconstruction Error\noffsetFull : Off set value for avoding overflow when calculating full gradient\noffsetStoch : Off set value for avoding overflow when calculating stochastic gradient\nlogdir : The directory where intermediate files are saved, in every evalfreq (e.g. 5000) iteration.\nperm : Whether the data matrix is shuffled at random.\n\nOutput Arguments\n\nW : Eigen vectors of covariance matrix (No. columns of the data matrix × dim)\nλ : Eigen values (dim × dim)\nV : Loading vectors of covariance matrix (No. rows of the data matrix × dim)\n\nReference\n\nRSVRG-PCA : Hongyi Zhang, et. al., 2016, Hiroyuki Sato, et. al., 2017\n\n\n\n\n\n"
},

{
    "location": "juliaapi.html#RSVRG-1",
    "page": "Julia API",
    "title": "RSVRG",
    "category": "section",
    "text": "rsvrg(;input::AbstractString=\"\", outdir::Union{Nothing,AbstractString}=nothing, scale::AbstractString=\"ftt\", pseudocount::Number=1.0, rowmeanlist::AbstractString=\"\", rowvarlist::AbstractString=\"\",colsumlist::AbstractString=\"\", dim::Number=3, stepsize::Number=0.1, numepoch::Number=3, scheduling::AbstractString=\"robbins-monro\", g::Number=0.9, epsilon::Number=1.0e-8, lower::Number=0, upper::Number=1.0f+38, expvar::Number=0.1f0, evalfreq::Number=5000, offsetFull::Number=1f-20, offsetStoch::Number=1f-6, logdir::Union{Nothing,AbstractString}=nothing, perm::Bool=false)"
},

{
    "location": "commandline.html#",
    "page": "Command line Tool",
    "title": "Command line Tool",
    "category": "page",
    "text": ""
},

{
    "location": "commandline.html#OnlinePCA.jl-(Command-line-tool)-1",
    "page": "Command line Tool",
    "title": "OnlinePCA.jl (Command line tool)",
    "category": "section",
    "text": "All functions can be performed as command line tool in shell window and same options in OnlinePCA.jl (Julia API) are available.After installation of OnlinePCA.jl, command line tools are saved at YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/.The functions can be performed as below."
},

{
    "location": "commandline.html#Binarization-1",
    "page": "Command line Tool",
    "title": "Binarization",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/csv2bin \\\n--csvfile Data.csv \\\n--binfile OUTDIR/Data.zst"
},

{
    "location": "commandline.html#Summarization-1",
    "page": "Command line Tool",
    "title": "Summarization",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/sumr \\\n--binfile OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--pseudocount 1.0"
},

{
    "location": "commandline.html#Filtering-1",
    "page": "Command line Tool",
    "title": "Filtering",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/filtering \\\n--binfile OUTDIR/Data.zst \\\n--featurelist OUTDIR/Feature_Means.csv \\\n--thr1 10 \\\n--direct1 \"+\" \\\n--outdir OUTDIR"
},

{
    "location": "commandline.html#Identifying-Highly-Variable-Genes-1",
    "page": "Command line Tool",
    "title": "Identifying Highly Variable Genes",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/hvg \\\n--binfile OUTDIR/Data.zst \\\n--rowmeanlist OUTDIR/Feature_Means.csv \\\n--rowvarlist OUTDIR/Feature_Vars.csv \\\n--rowcv2list OUTDIR/Feature_CV2s.csv \\\n--outdir OUTDIR"
},

{
    "location": "commandline.html#Oja-1",
    "page": "Command line Tool",
    "title": "Oja",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/oja \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--rowvarlist OUTDIR/Feature_LogVars.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 3 \\\n--scheduling \"robbins-monro\" \\\n--g 0.9 \\\n--epsilon 1.0e-8 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetStoch 1f-6 \\\n--logdir OUTDIR \\\n--perm false"
},

{
    "location": "commandline.html#CCIPCA-1",
    "page": "Command line Tool",
    "title": "CCIPCA",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/ccipca \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--rowvarlist OUTDIR/Feature_LogVars.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 3 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetStoch 1f-15 \\\n--logdir OUTDIR \\\n--perm false"
},

{
    "location": "commandline.html#GD-1",
    "page": "Command line Tool",
    "title": "GD",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/gd \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--masklist OUTDIR/MASKLIST.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 5 \\\n--scheduling \"robbins-monro\" \\\n--g 0.9 \\\n--epsilon 1.0e-8 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetFull 1f-20 \\\n--logdir OUTDIR \\\n--perm false"
},

{
    "location": "commandline.html#RSGD-1",
    "page": "Command line Tool",
    "title": "RSGD",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/rsgd \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--masklist OUTDIR/MASKLIST.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 5 \\\n--scheduling \"robbins-monro\" \\\n--g 0.9 \\\n--epsilon 1.0e-8 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetStoch 1f-6 \\\n--logdir OUTDIR \\\n--perm false"
},

{
    "location": "commandline.html#SVRG-1",
    "page": "Command line Tool",
    "title": "SVRG",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/svrg \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--masklist OUTDIR/MASKLIST.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 5 \\\n--scheduling \"robbins-monro\" \\\n--g 0.9 \\\n--epsilon 1.0e-8 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetFull 1f-20 \\\n--offsetStoch 1f-6 \\\n--logdir OUTDIR \\\n--perm false"
},

{
    "location": "commandline.html#RSVRG-1",
    "page": "Command line Tool",
    "title": "RSVRG",
    "category": "section",
    "text": "shell> julia YOUR_HOME_DIR/.julia/v0.x/OnlinePCA/bin/rsvrg \\\n--input OUTDIR/Data.zst \\\n--outdir OUTDIR \\\n--scale ftt \\\n--pseudocount 1 \\\n--rowmeanlist OUTDIR/Feature_LogMeans.csv \\\n--colsumlist OUTDIR/Sample_NoCounts.csv \\\n--masklist OUTDIR/MASKLIST.csv \\\n--dim 3 \\\n--stepsize 0.1 \\\n--numepoch 5 \\\n--scheduling \"robbins-monro\" \\\n--g 0.9 \\\n--epsilon 1.0e-8 \\\n--lower 0 \\\n--upper 1.0f+38 \\\n--expvar 0.1f0 \\\n--evalfreq 5000 \\\n--offsetFull 1f-20 \\\n--offsetStoch 1f-6 \\\n--logdir OUTDIR \\\n--perm false"
},

]}
